class_names = [
"Corn_(maize)___Common_rust",
"Pepper__bell___Bacterial_spot",
"Pepper__bell___healthy",
"Potato___Early_blight",
"Potato___Late_blight",
"Potato___healthy",
"Tomato_Bacterial_spot",
"Tomato_Early_blight",
"Tomato_Late_blight",
"Tomato_Leaf_Mold"
]
disease_info = {
    "Corn_(maize)___Common_rust": {
        "Description": "Common Rust is a fungal disease of maize caused by Puccinia sorghi. It mainly affects the leaves and can reduce crop yield if not controlled in time.",
        "Symptoms": "Small reddish-brown pustules on both sides of leaves, yellowing of leaves, reduced plant growth, and premature drying in severe infections.",
        "Treatment": "Spray fungicides such as Azoxystrobin, Propiconazole, or Mancozeb as recommended by agricultural experts.",
        "Prevention": "Grow resistant maize varieties, follow crop rotation, avoid overcrowding, and remove infected plant debris after harvest.",
        "Fertilizer": "Apply balanced NPK fertilizer (20:20:20) along with Zinc and Potash if required.",
        "Pesticide": "Azoxystrobin 18.2% + Difenoconazole 11.4% SC or Propiconazole 25% EC.",
        "Weather": "Disease spreads rapidly in cool (15–25°C) and humid weather with frequent rainfall or dew.",
        "Water": "Avoid excessive irrigation and waterlogging. Maintain proper field drainage.",
        "Soil": "Well-drained fertile loamy soil with pH between 6.0 and 7.5.",
        "Sunlight": "Requires 6–8 hours of direct sunlight daily.",
        "Severity": "Medium",
        "Recovery_Time": "10–20 Days after proper fungicide application.",
        "Estimated_Cost": "₹700–₹1800 per acre",
        "Nutrient_Deficiency": "Potassium and Zinc deficiency can weaken the crop and increase disease susceptibility.",
        "Organic_Control": "Spray neem oil, use Trichoderma-based biofungicides, and maintain field sanitation.",
        "Government_Advice": "Follow Integrated Disease Management (IDM) practices and consult the nearest Krishi Vigyan Kendra (KVK) or Agriculture Department for severe outbreaks."
    },
    "Pepper__bell___Bacterial_spot": {
        "Description": "Bacterial Spot is caused by Xanthomonas bacteria and affects leaves and fruits.",
        "Symptoms": "Dark water-soaked spots, yellow halos, leaf drop.",
        "Treatment": "Apply copper-based bactericide every 7–10 days.",
        "Prevention": "Use disease-free seeds, avoid overhead irrigation.",
        "Fertilizer": "NPK 19:19:19 + Micronutrients",
        "Pesticide": "Copper Oxychloride",
        "Weather": "Warm and humid weather favors disease.",
        "Water": "Use drip irrigation.",
        "Soil": "Well-drained loamy soil (pH 6–7).",
        "Sunlight": "6–8 hours/day.",
        "Severity": "High",
        "Recovery_Time": "2–3 Weeks",
        "Estimated_Cost": "₹800–₹1800 / acre",
        "Nutrient_Deficiency": "Calcium & Potassium deficiency may increase infection.",
        "Organic_Control": "Neem oil spray + Bacillus subtilis.",
        "Government_Advice": "Consult nearest KVK if infection spreads rapidly."
    },

    "Pepper__bell___healthy": {
        "Description": "Healthy pepper plant with no visible disease symptoms.",
        "Symptoms": "Healthy green leaves and vigorous growth.",
        "Treatment": "No treatment required.",
        "Prevention": "Maintain proper irrigation and nutrition.",
        "Fertilizer": "Vermicompost + NPK 19:19:19",
        "Pesticide": "Not Required",
        "Weather": "20–28°C",
        "Water": "Keep soil moist.",
        "Soil": "Fertile loamy soil.",
        "Sunlight": "6–8 hours/day.",
        "Severity": "None",
        "Recovery_Time": "Already Healthy",
        "Estimated_Cost": "₹0",
        "Nutrient_Deficiency": "None",
        "Organic_Control": "Regular compost application.",
        "Government_Advice": "Follow standard cultivation practices."
    },

    "Potato___Early_blight": {
        "Description": "A fungal disease caused by Alternaria solani.",
        "Symptoms": "Brown concentric rings on leaves, yellowing.",
        "Treatment": "Spray Mancozeb or Chlorothalonil.",
        "Prevention": "Crop rotation and remove infected leaves.",
        "Fertilizer": "NPK 12:32:16",
        "Pesticide": "Mancozeb",
        "Weather": "Warm humid weather.",
        "Water": "Moderate irrigation.",
        "Soil": "Well-drained sandy loam.",
        "Sunlight": "6–8 hours/day.",
        "Severity": "Medium",
        "Recovery_Time": "10–15 Days",
        "Estimated_Cost": "₹700–₹1400 / acre",
        "Nutrient_Deficiency": "Potassium deficiency.",
        "Organic_Control": "Neem oil + Trichoderma.",
        "Government_Advice": "Follow Integrated Disease Management."
    },

    "Potato___Late_blight": {
        "Description": "A destructive disease caused by Phytophthora infestans.",
        "Symptoms": "Black lesions, white fungal growth, tuber rot.",
        "Treatment": "Metalaxyl + Mancozeb spray.",
        "Prevention": "Avoid waterlogging and remove infected plants.",
        "Fertilizer": "Balanced NPK with Potassium.",
        "Pesticide": "Metalaxyl + Mancozeb",
        "Weather": "Cool and humid weather.",
        "Water": "Avoid standing water.",
        "Soil": "Well-drained loamy soil.",
        "Sunlight": "Full sunlight.",
        "Severity": "High",
        "Recovery_Time": "2–3 Weeks",
        "Estimated_Cost": "₹1000–₹2500 / acre",
        "Nutrient_Deficiency": "Low Potassium.",
        "Organic_Control": "Neem extract + Trichoderma.",
        "Government_Advice": "Report severe outbreak to Agriculture Department."
    },

    "Potato___healthy": {
        "Description": "Healthy potato crop without disease.",
        "Symptoms": "Healthy foliage and tubers.",
        "Treatment": "No treatment required.",
        "Prevention": "Regular monitoring.",
        "Fertilizer": "NPK 19:19:19 + Organic manure.",
        "Pesticide": "Not Required",
        "Weather": "18–22°C",
        "Water": "Maintain uniform moisture.",
        "Soil": "Fertile sandy loam.",
        "Sunlight": "6–8 hours/day.",
        "Severity": "None",
        "Recovery_Time": "Already Healthy",
        "Estimated_Cost": "₹0",
        "Nutrient_Deficiency": "None",
        "Organic_Control": "Compost + Vermicompost.",
        "Government_Advice": "Continue recommended cultivation practices."
    },
        "Tomato_Bacterial_spot": {
        "Description": "Bacterial Spot is caused by Xanthomonas bacteria. It affects tomato leaves, stems, and fruits, reducing both yield and fruit quality.",
        "Symptoms": "Small dark water-soaked spots on leaves, yellow halos, black fruit lesions, leaf drop.",
        "Treatment": "Spray Copper Oxychloride or Copper Hydroxide every 7–10 days.",
        "Prevention": "Use certified seeds, avoid overhead irrigation, rotate crops, remove infected debris.",
        "Fertilizer": "NPK 19:19:19 + Micronutrients",
        "Pesticide": "Copper Oxychloride 50% WP",
        "Weather": "Warm (25–30°C) and humid weather.",
        "Water": "Use drip irrigation and avoid leaf wetness.",
        "Soil": "Well-drained loamy soil (pH 6.0–6.8).",
        "Sunlight": "6–8 hours/day.",
        "Severity": "High",
        "Recovery_Time": "2–3 Weeks",
        "Estimated_Cost": "₹800–₹1800 / acre",
        "Nutrient_Deficiency": "Calcium and Potassium deficiency.",
        "Organic_Control": "Neem oil + Bacillus subtilis.",
        "Government_Advice": "Consult nearest KVK if infection spreads rapidly."
    },

    "Tomato_Early_blight": {
        "Description": "Early Blight is caused by Alternaria solani and mainly attacks older tomato leaves.",
        "Symptoms": "Brown concentric spots, yellow leaves, premature leaf drop.",
        "Treatment": "Spray Mancozeb or Chlorothalonil fungicide.",
        "Prevention": "Crop rotation, proper spacing, remove infected leaves.",
        "Fertilizer": "NPK 12:32:16 + Organic Compost",
        "Pesticide": "Mancozeb 75% WP",
        "Weather": "Warm and humid conditions.",
        "Water": "Moderate irrigation.",
        "Soil": "Well-drained loamy soil.",
        "Sunlight": "6–8 hours/day.",
        "Severity": "Medium",
        "Recovery_Time": "10–15 Days",
        "Estimated_Cost": "₹700–₹1500 / acre",
        "Nutrient_Deficiency": "Potassium deficiency.",
        "Organic_Control": "Neem oil + Trichoderma.",
        "Government_Advice": "Follow Integrated Disease Management (IDM)."
    },

    "Tomato_Late_blight": {
        "Description": "Late Blight is caused by Phytophthora infestans and spreads rapidly during cool, humid weather.",
        "Symptoms": "Dark brown lesions, white fungal growth, fruit rot.",
        "Treatment": "Spray Metalaxyl + Mancozeb immediately.",
        "Prevention": "Avoid waterlogging, improve air circulation, remove infected plants.",
        "Fertilizer": "Balanced NPK with Potassium",
        "Pesticide": "Metalaxyl + Mancozeb",
        "Weather": "Cool (10–20°C) and humid weather.",
        "Water": "Avoid standing water.",
        "Soil": "Well-drained fertile loamy soil.",
        "Sunlight": "Full sunlight.",
        "Severity": "High",
        "Recovery_Time": "2–3 Weeks",
        "Estimated_Cost": "₹1000–₹2500 / acre",
        "Nutrient_Deficiency": "Potassium & Calcium deficiency.",
        "Organic_Control": "Neem oil + Trichoderma.",
        "Government_Advice": "Report severe outbreaks to KVK."
    },

    "Tomato_Leaf_Mold": {
        "Description": "Leaf Mold is caused by Passalora fulva and develops in humid environments.",
        "Symptoms": "Yellow patches on upper leaf surface with olive-green mold underneath.",
        "Treatment": "Apply Chlorothalonil or Copper fungicide.",
        "Prevention": "Reduce humidity, improve ventilation, avoid overhead watering.",
        "Fertilizer": "Balanced NPK with Calcium & Magnesium.",
        "Pesticide": "Chlorothalonil",
        "Weather": "18–25°C with high humidity.",
        "Water": "Drip irrigation recommended.",
        "Soil": "Well-drained loamy soil.",
        "Sunlight": "6–8 hours/day.",
        "Severity": "Medium",
        "Recovery_Time": "10–14 Days",
        "Estimated_Cost": "₹700–₹1500 / acre",
        "Nutrient_Deficiency": "Calcium and Magnesium deficiency.",
        "Organic_Control": "Neem oil + Compost Tea.",
        "Government_Advice": "Follow recommended IDM practices."
    },

}